//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveletStudio.Designer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveletStudio.Designer.Resources.DesignerResources", typeof(DesignerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default)
        ///English (United States)
        ///Portuguese (Brazil).
        /// </summary>
        internal static string AvailableLanguages {
            get {
                return ResourceManager.GetString("AvailableLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separator.
        /// </summary>
        internal static string ColumnSeparator {
            get {
                return ResourceManager.GetString("ColumnSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution Mode.
        /// </summary>
        internal static string ConvolutionMode {
            get {
                return ResourceManager.GetString("ConvolutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Sources.
        /// </summary>
        internal static string CreateSignal {
            get {
                return ResourceManager.GetString("CreateSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# File.
        /// </summary>
        internal static string CSharpFile {
            get {
                return ResourceManager.GetString("CSharpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic (slower, uses less memory).
        /// </summary>
        internal static string DynamicTrigonometricValues {
            get {
                return ResourceManager.GetString("DynamicTrigonometricValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before performing any operation is necessary to select a source. 
        ///Click in the Signal tab and select a signal source..
        /// </summary>
        internal static string ErrorInvalidOriginalSignal {
            get {
                return ResourceManager.GetString("ErrorInvalidOriginalSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Signal.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension size (0 to use next power of 2).
        /// </summary>
        internal static string ExtensionSize {
            get {
                return ResourceManager.GetString("ExtensionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        internal static string FFT {
            get {
                return ResourceManager.GetString("FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be opened.
        /// </summary>
        internal static string FileCouldntBeOpened {
            get {
                return ResourceManager.GetString("FileCouldntBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be saved.
        /// </summary>
        internal static string FileCouldntBeSaved {
            get {
                return ResourceManager.GetString("FileCouldntBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Time.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get help in this application at the folowing site.
        /// </summary>
        internal static string HelpLinkMessage {
            get {
                return ResourceManager.GetString("HelpLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore first row.
        /// </summary>
        internal static string IgnoreFirstRow {
            get {
                return ResourceManager.GetString("IgnoreFirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the last sample.
        /// </summary>
        internal static string IgnoreLastSample {
            get {
                return ResourceManager.GetString("IgnoreLastSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Signal.
        /// </summary>
        internal static string LoadSignal {
            get {
                return ResourceManager.GetString("LoadSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Operations.
        /// </summary>
        internal static string Logic {
            get {
                return ResourceManager.GetString("Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model threw a stack overflow exception.
        /// </summary>
        internal static string ModelThrewStackOverflow {
            get {
                return ResourceManager.GetString("ModelThrewStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document.
        /// </summary>
        internal static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string NewDocumentChar {
            get {
                return ResourceManager.GetString("NewDocumentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Size.
        /// </summary>
        internal static string PreviousSize {
            get {
                return ResourceManager.GetString("PreviousSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Finish.
        /// </summary>
        internal static string RampFinish {
            get {
                return ResourceManager.GetString("RampFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Start.
        /// </summary>
        internal static string RampStart {
            get {
                return ResourceManager.GetString("RampStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program needs to be restarted in order to apply new settings..
        /// </summary>
        internal static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return only valid samples.
        /// </summary>
        internal static string ReturnOnlyValid {
            get {
                return ResourceManager.GetString("ReturnOnlyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value to zero in the end.
        /// </summary>
        internal static string ReturnToZero {
            get {
                return ResourceManager.GetString("ReturnToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Routing.
        /// </summary>
        internal static string Routing {
            get {
                return ResourceManager.GetString("Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample time interval.
        /// </summary>
        internal static string SamplingInterval {
            get {
                return ResourceManager.GetString("SamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rate (Hz).
        /// </summary>
        internal static string SamplingRate {
            get {
                return ResourceManager.GetString("SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes before closing?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        internal static string ScalarOperation_Text {
            get {
                return ResourceManager.GetString("ScalarOperation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        internal static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First column contains signal name.
        /// </summary>
        internal static string SignalNameInFirstColumn {
            get {
                return ResourceManager.GetString("SignalNameInFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal start time.
        /// </summary>
        internal static string SignalStart {
            get {
                return ResourceManager.GetString("SignalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Templates.
        /// </summary>
        internal static string SignalTemplates {
            get {
                return ResourceManager.GetString("SignalTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.waveletstudio.net.
        /// </summary>
        internal static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Samples.
        /// </summary>
        internal static string SortSamples {
            get {
                return ResourceManager.GetString("SortSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        internal static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use trigonometric table (faster).
        /// </summary>
        internal static string UseLookupTable {
            get {
                return ResourceManager.GetString("UseLookupTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet Studio.
        /// </summary>
        internal static string WaveletStudio {
            get {
                return ResourceManager.GetString("WaveletStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet Studio Document.
        /// </summary>
        internal static string WaveletStudioDocument {
            get {
                return ResourceManager.GetString("WaveletStudioDocument", resourceCulture);
            }
        }
    }
}
