//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveletStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveletStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute value of a signal..
        /// </summary>
        public static string AbsoluteDescription {
            get {
                return ResourceManager.GetString("AbsoluteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Value.
        /// </summary>
        public static string AbsoluteValue {
            get {
                return ResourceManager.GetString("AbsoluteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        public static string Amplitude {
            get {
                return ResourceManager.GetString("Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude of the signal..
        /// </summary>
        public static string AmplitudeDescription {
            get {
                return ResourceManager.GetString("AmplitudeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation.
        /// </summary>
        public static string Approximation {
            get {
                return ResourceManager.GetString("Approximation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximation Level.
        /// </summary>
        public static string ApproximationLevel {
            get {
                return ResourceManager.GetString("ApproximationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separator.
        /// </summary>
        public static string ColumnSeparator {
            get {
                return ResourceManager.GetString("ColumnSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separator value (, |, etc)..
        /// </summary>
        public static string ColumnSeparatorDescription {
            get {
                return ResourceManager.GetString("ColumnSeparatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution.
        /// </summary>
        public static string Convolution {
            get {
                return ResourceManager.GetString("Convolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute convolution of two inputs.
        /// </summary>
        public static string ConvolutionDescription {
            get {
                return ResourceManager.GetString("ConvolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution Mode.
        /// </summary>
        public static string convolutionmode {
            get {
                return ResourceManager.GetString("convolutionmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Places.
        /// </summary>
        public static string DecimalPlaces {
            get {
                return ResourceManager.GetString("DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of decimal places..
        /// </summary>
        public static string DecimalPlacesDescription {
            get {
                return ResourceManager.GetString("DecimalPlacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time delay..
        /// </summary>
        public static string DelayDescription {
            get {
                return ResourceManager.GetString("DelayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract and output elements of vector signal..
        /// </summary>
        public static string DemuxDescription {
            get {
                return ResourceManager.GetString("DemuxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Level.
        /// </summary>
        public static string DetailsLevel {
            get {
                return ResourceManager.GetString("DetailsLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsample.
        /// </summary>
        public static string Downsample {
            get {
                return ResourceManager.GetString("Downsample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreases the sampling rate of the input by keeping every odd sample starting with the first sample..
        /// </summary>
        public static string DownsampleDescription {
            get {
                return ResourceManager.GetString("DownsampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet decomposition block.
        /// </summary>
        public static string DWTDescription {
            get {
                return ResourceManager.GetString("DWTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic (slower, uses less memory).
        /// </summary>
        public static string dynamictrigonometricvalues {
            get {
                return ResourceManager.GetString("dynamictrigonometricvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before performing any operation is necessary to select a source. 
        ///Click in the Signal tab and select a signal source..
        /// </summary>
        public static string errorinvalidoriginalsignal {
            get {
                return ResourceManager.GetString("errorinvalidoriginalsignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string ExportToCSV {
            get {
                return ResourceManager.GetString("ExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports a signal to a CSV file.
        /// </summary>
        public static string ExportToCSVDescription {
            get {
                return ResourceManager.GetString("ExportToCSVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Mode.
        /// </summary>
        public static string ExtensionMode {
            get {
                return ResourceManager.GetString("ExtensionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how the signal should be extended during the transform..
        /// </summary>
        public static string ExtensionModeDescription {
            get {
                return ResourceManager.GetString("ExtensionModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Size.
        /// </summary>
        public static string ExtensionSize {
            get {
                return ResourceManager.GetString("ExtensionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension size (0 to use next power of 2)..
        /// </summary>
        public static string ExtensionSizeDescription {
            get {
                return ResourceManager.GetString("ExtensionSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor used in the operation..
        /// </summary>
        public static string FactorDescription {
            get {
                return ResourceManager.GetString("FactorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        public static string FFT {
            get {
                return ResourceManager.GetString("FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute fast Fourier transform (FFT) of input..
        /// </summary>
        public static string FFTDescription {
            get {
                return ResourceManager.GetString("FFTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT Mode.
        /// </summary>
        public static string FFTMode {
            get {
                return ResourceManager.GetString("FFTMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FFT mode to be used on convolution..
        /// </summary>
        public static string FFTModeDescription {
            get {
                return ResourceManager.GetString("FFTModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute or relative path to the file..
        /// </summary>
        public static string FilePathDescription {
            get {
                return ResourceManager.GetString("FilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Time.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal finish time..
        /// </summary>
        public static string FinishDescription {
            get {
                return ResourceManager.GetString("FinishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Size.
        /// </summary>
        public static string FrameSize {
            get {
                return ResourceManager.GetString("FrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frame size used in the block..
        /// </summary>
        public static string FrameSizeDescription {
            get {
                return ResourceManager.GetString("FrameSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency used in the block..
        /// </summary>
        public static string FrequencyDescription {
            get {
                return ResourceManager.GetString("FrequencyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Wavelet Decomposition (IDWT) block..
        /// </summary>
        public static string IDWTDescription {
            get {
                return ResourceManager.GetString("IDWTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute inverse fast Fourier transform (IFFT) of input..
        /// </summary>
        public static string IFFTDescription {
            get {
                return ResourceManager.GetString("IFFTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore first row.
        /// </summary>
        public static string IgnoreFirstRow {
            get {
                return ResourceManager.GetString("IgnoreFirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore first row when reading the file..
        /// </summary>
        public static string IgnoreFirstRowDescription {
            get {
                return ResourceManager.GetString("IgnoreFirstRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the last sample.
        /// </summary>
        public static string IgnoreLastSample {
            get {
                return ResourceManager.GetString("IgnoreLastSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether the last sample will be included in signal..
        /// </summary>
        public static string IgnoreLastSampleDescription {
            get {
                return ResourceManager.GetString("IgnoreLastSampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from CSV.
        /// </summary>
        public static string ImportFromCSV {
            get {
                return ResourceManager.GetString("ImportFromCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a signal based on a CSV file..
        /// </summary>
        public static string ImportFromCSVDescription {
            get {
                return ResourceManager.GetString("ImportFromCSVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Signal Name in First Column.
        /// </summary>
        public static string IncludeSignalNameInFirstColumn {
            get {
                return ResourceManager.GetString("IncludeSignalNameInFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, the block includes the signal name in first column..
        /// </summary>
        public static string IncludeSignalNameInFirstColumnDescription {
            get {
                return ResourceManager.GetString("IncludeSignalNameInFirstColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Inputs.
        /// </summary>
        public static string InputCount {
            get {
                return ResourceManager.GetString("InputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of inputs of the block..
        /// </summary>
        public static string InputCountDescription {
            get {
                return ResourceManager.GetString("InputCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Sampling Rate.
        /// </summary>
        public static string KeepSamplingRate {
            get {
                return ResourceManager.GetString("KeepSamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, keeps the original sampling rate, changing the signal start and finish times..
        /// </summary>
        public static string KeepSamplingRateDescription {
            get {
                return ResourceManager.GetString("KeepSamplingRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of levels to decompose..
        /// </summary>
        public static string LevelDescription {
            get {
                return ResourceManager.GetString("LevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean value used in the block..
        /// </summary>
        public static string MeanDescription {
            get {
                return ResourceManager.GetString("MeanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode used in the block..
        /// </summary>
        public static string ModeDescription {
            get {
                return ResourceManager.GetString("ModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from the origin..
        /// </summary>
        public static string OffsetDescription {
            get {
                return ResourceManager.GetString("OffsetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math operation used in the block..
        /// </summary>
        public static string OperationDescription {
            get {
                return ResourceManager.GetString("OperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Outputs.
        /// </summary>
        public static string OutputCount {
            get {
                return ResourceManager.GetString("OutputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of outputs of the block..
        /// </summary>
        public static string OutputCountDescription {
            get {
                return ResourceManager.GetString("OutputCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase used in the block..
        /// </summary>
        public static string PhaseDescription {
            get {
                return ResourceManager.GetString("PhaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Type.
        /// </summary>
        public static string ProcessingType {
            get {
                return ResourceManager.GetString("ProcessingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of action done by the block..
        /// </summary>
        public static string ProcessingTypeDescription {
            get {
                return ResourceManager.GetString("ProcessingTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Finish.
        /// </summary>
        public static string RampFinish {
            get {
                return ResourceManager.GetString("RampFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish of the ramp in time..
        /// </summary>
        public static string RampFinishDescription {
            get {
                return ResourceManager.GetString("RampFinishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Start.
        /// </summary>
        public static string RampStart {
            get {
                return ResourceManager.GetString("RampStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp start time..
        /// </summary>
        public static string RampStartDescription {
            get {
                return ResourceManager.GetString("RampStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconstruction.
        /// </summary>
        public static string Reconstruction {
            get {
                return ResourceManager.GetString("Reconstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition Count.
        /// </summary>
        public static string RepetitionCount {
            get {
                return ResourceManager.GetString("RepetitionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repetition count used in the block..
        /// </summary>
        public static string RepetitionCountDescription {
            get {
                return ResourceManager.GetString("RepetitionCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return only valid samples.
        /// </summary>
        public static string ReturnOnlyValid {
            get {
                return ResourceManager.GetString("ReturnOnlyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, the block returns only the valid samples (central area)..
        /// </summary>
        public static string ReturnOnlyValidDescription {
            get {
                return ResourceManager.GetString("ReturnOnlyValidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Zero.
        /// </summary>
        public static string ReturnToZero {
            get {
                return ResourceManager.GetString("ReturnToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value to zero in the end..
        /// </summary>
        public static string ReturnToZeroDescription {
            get {
                return ResourceManager.GetString("ReturnToZeroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample time interval.
        /// </summary>
        public static string SamplingInterval {
            get {
                return ResourceManager.GetString("SamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample time interval used in the block..
        /// </summary>
        public static string SamplingIntervalDescription {
            get {
                return ResourceManager.GetString("SamplingIntervalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rate (Hz).
        /// </summary>
        public static string SamplingRate {
            get {
                return ResourceManager.GetString("SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling rate used on sampling..
        /// </summary>
        public static string SamplingRateDescription {
            get {
                return ResourceManager.GetString("SamplingRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        public static string scalaroperation_text {
            get {
                return ResourceManager.GetString("scalaroperation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Indexes.
        /// </summary>
        public static string SignalIndexes {
            get {
                return ResourceManager.GetString("SignalIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes of the signals to be copied in the output. One line per output, separated with commas (,)..
        /// </summary>
        public static string SignalIndexesDescription {
            get {
                return ResourceManager.GetString("SignalIndexesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First column contains signal name.
        /// </summary>
        public static string SignalNameInFirstColumn {
            get {
                return ResourceManager.GetString("SignalNameInFirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, the first column contains the name of the signal..
        /// </summary>
        public static string SignalNameInFirstColumnDescription {
            get {
                return ResourceManager.GetString("SignalNameInFirstColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Names.
        /// </summary>
        public static string SignalNames {
            get {
                return ResourceManager.GetString("SignalNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal names used in the output (optional, one per line)..
        /// </summary>
        public static string SignalNamesDescription {
            get {
                return ResourceManager.GetString("SignalNamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Start.
        /// </summary>
        public static string SignalStart {
            get {
                return ResourceManager.GetString("SignalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal start time..
        /// </summary>
        public static string SignalStartDescription {
            get {
                return ResourceManager.GetString("SignalStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Templates.
        /// </summary>
        public static string signaltemplates {
            get {
                return ResourceManager.GetString("signaltemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Samples.
        /// </summary>
        public static string SortSamples {
            get {
                return ResourceManager.GetString("SortSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, the block will sort the samples before execute..
        /// </summary>
        public static string SortSamplesDescription {
            get {
                return ResourceManager.GetString("SortSamplesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Deviation.
        /// </summary>
        public static string StandardDeviation {
            get {
                return ResourceManager.GetString("StandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation value used in the block..
        /// </summary>
        public static string StandardDeviationDescription {
            get {
                return ResourceManager.GetString("StandardDeviationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal start time..
        /// </summary>
        public static string StartDescription {
            get {
                return ResourceManager.GetString("StartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Threshold.
        /// </summary>
        public static string StaticThreshold {
            get {
                return ResourceManager.GetString("StaticThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign the switch threshold that determines which input the block passes to the output..
        /// </summary>
        public static string StaticThresholdDescription {
            get {
                return ResourceManager.GetString("StaticThresholdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Criteria.
        /// </summary>
        public static string SwitchCriteria {
            get {
                return ResourceManager.GetString("SwitchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria for select the output..
        /// </summary>
        public static string SwitchCriteriaDescription {
            get {
                return ResourceManager.GetString("SwitchCriteriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signal generation template used by the block..
        /// </summary>
        public static string TemplateNameDescription {
            get {
                return ResourceManager.GetString("TemplateNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template {0} does not exist..
        /// </summary>
        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a signal based on a text..
        /// </summary>
        public static string TextBlockDescription {
            get {
                return ResourceManager.GetString("TextBlockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text used in the block..
        /// </summary>
        public static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use trigonometric table (faster).
        /// </summary>
        public static string uselookuptable {
            get {
                return ResourceManager.GetString("uselookuptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar value..
        /// </summary>
        public static string ValueDescription {
            get {
                return ResourceManager.GetString("ValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet Name.
        /// </summary>
        public static string WaveletName {
            get {
                return ResourceManager.GetString("WaveletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet function to be used..
        /// </summary>
        public static string WaveletNameDescription {
            get {
                return ResourceManager.GetString("WaveletNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wavelet {0} does not exist..
        /// </summary>
        public static string WaveletNameNotFound {
            get {
                return ResourceManager.GetString("WaveletNameNotFound", resourceCulture);
            }
        }
    }
}
