//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveletStudio.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveletStudio.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default)
        ///English (United States)
        ///Portuguese (Brazil).
        /// </summary>
        internal static string AvailableLanguages {
            get {
                return ResourceManager.GetString("AvailableLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separator.
        /// </summary>
        internal static string columnseparator {
            get {
                return ResourceManager.GetString("columnseparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution Mode.
        /// </summary>
        internal static string convolutionmode {
            get {
                return ResourceManager.GetString("convolutionmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# File.
        /// </summary>
        internal static string CSharpFile {
            get {
                return ResourceManager.GetString("CSharpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic (slower, uses less memory).
        /// </summary>
        internal static string dynamictrigonometricvalues {
            get {
                return ResourceManager.GetString("dynamictrigonometricvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before performing any operation is necessary to select a source. 
        ///Click in the Signal tab and select a signal source..
        /// </summary>
        internal static string errorinvalidoriginalsignal {
            get {
                return ResourceManager.GetString("errorinvalidoriginalsignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension size (0 to use next power of 2).
        /// </summary>
        internal static string extensionsize {
            get {
                return ResourceManager.GetString("extensionsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        internal static string fft {
            get {
                return ResourceManager.GetString("fft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be opened.
        /// </summary>
        internal static string FileCouldntBeOpened {
            get {
                return ResourceManager.GetString("FileCouldntBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be saved.
        /// </summary>
        internal static string FileCouldntBeSaved {
            get {
                return ResourceManager.GetString("FileCouldntBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string filepath {
            get {
                return ResourceManager.GetString("filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Time.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        internal static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get help in this application at the folowing site.
        /// </summary>
        internal static string HelpLinkMessage {
            get {
                return ResourceManager.GetString("HelpLinkMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon icoColor {
            get {
                object obj = ResourceManager.GetObject("icoColor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icoCopy {
            get {
                object obj = ResourceManager.GetObject("icoCopy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconClose {
            get {
                object obj = ResourceManager.GetObject("iconClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconGrid {
            get {
                object obj = ResourceManager.GetObject("iconGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconPrint {
            get {
                object obj = ResourceManager.GetObject("iconPrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconPrintPreview {
            get {
                object obj = ResourceManager.GetObject("iconPrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconPrintSettings {
            get {
                object obj = ResourceManager.GetObject("iconPrintSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconStretch {
            get {
                object obj = ResourceManager.GetObject("iconStretch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon icoPaste {
            get {
                object obj = ResourceManager.GetObject("icoPaste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore first row.
        /// </summary>
        internal static string ignorefirstrow {
            get {
                return ResourceManager.GetString("ignorefirstrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the last sample.
        /// </summary>
        internal static string ignorelastsample {
            get {
                return ResourceManager.GetString("ignorelastsample", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap imgAbsoluteValueBlock {
            get {
                object obj = ResourceManager.GetObject("imgAbsoluteValueBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAbsoluteValueBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgAbsoluteValueBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAnd {
            get {
                object obj = ResourceManager.GetObject("imgAnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAndMini {
            get {
                object obj = ResourceManager.GetObject("imgAndMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgConvolutionBlock {
            get {
                object obj = ResourceManager.GetObject("imgConvolutionBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgConvolutionBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgConvolutionBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCosine {
            get {
                object obj = ResourceManager.GetObject("imgCosine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDeextend {
            get {
                object obj = ResourceManager.GetObject("imgDeextend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDeextendMini {
            get {
                object obj = ResourceManager.GetObject("imgDeextendMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDemuxBlock {
            get {
                object obj = ResourceManager.GetObject("imgDemuxBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDemuxBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgDemuxBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDivideMini {
            get {
                object obj = ResourceManager.GetObject("imgDivideMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDownSampleBlock {
            get {
                object obj = ResourceManager.GetObject("imgDownSampleBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDownSampleBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgDownSampleBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDWTBlock {
            get {
                object obj = ResourceManager.GetObject("imgDWTBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDWTBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgDWTBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEqualsTo {
            get {
                object obj = ResourceManager.GetObject("imgEqualsTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEqualsToMini {
            get {
                object obj = ResourceManager.GetObject("imgEqualsToMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgExportToCSVBlock {
            get {
                object obj = ResourceManager.GetObject("imgExportToCSVBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFFTBlock {
            get {
                object obj = ResourceManager.GetObject("imgFFTBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgFFTBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgFFTBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgGreaterOrEqualsThanMini {
            get {
                object obj = ResourceManager.GetObject("imgGreaterOrEqualsThanMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgGreaterThanMini {
            get {
                object obj = ResourceManager.GetObject("imgGreaterThanMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgIDWTBlock {
            get {
                object obj = ResourceManager.GetObject("imgIDWTBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgIDWTBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgIDWTBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgIFFTBlock {
            get {
                object obj = ResourceManager.GetObject("imgIFFTBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgIFFTBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgIFFTBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgImportFromCSVBlock {
            get {
                object obj = ResourceManager.GetObject("imgImportFromCSVBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgImportFromTextBlock {
            get {
                object obj = ResourceManager.GetObject("imgImportFromTextBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgImportFromTextBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgImportFromTextBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInterpolationBlock {
            get {
                object obj = ResourceManager.GetObject("imgInterpolationBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInterpolationBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgInterpolationBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInvertBlock {
            get {
                object obj = ResourceManager.GetObject("imgInvertBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgInvertBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgInvertBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLessOrEqualsThanMini {
            get {
                object obj = ResourceManager.GetObject("imgLessOrEqualsThanMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLessThanMini {
            get {
                object obj = ResourceManager.GetObject("imgLessThanMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMultiply {
            get {
                object obj = ResourceManager.GetObject("imgMultiply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMultiplyMini {
            get {
                object obj = ResourceManager.GetObject("imgMultiplyMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMuxBlock {
            get {
                object obj = ResourceManager.GetObject("imgMuxBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMuxBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgMuxBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNotAndMini {
            get {
                object obj = ResourceManager.GetObject("imgNotAndMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNotEqualsToMini {
            get {
                object obj = ResourceManager.GetObject("imgNotEqualsToMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNotMini {
            get {
                object obj = ResourceManager.GetObject("imgNotMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNotOrMini {
            get {
                object obj = ResourceManager.GetObject("imgNotOrMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNotXorMini {
            get {
                object obj = ResourceManager.GetObject("imgNotXorMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgOrMini {
            get {
                object obj = ResourceManager.GetObject("imgOrMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRampFunctionBlock {
            get {
                object obj = ResourceManager.GetObject("imgRampFunctionBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRepeatBlock {
            get {
                object obj = ResourceManager.GetObject("imgRepeatBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRepeatBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgRepeatBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSampleBasedOperationBlock {
            get {
                object obj = ResourceManager.GetObject("imgSampleBasedOperationBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSampleBasedOperationBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgSampleBasedOperationBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSawtooth {
            get {
                object obj = ResourceManager.GetObject("imgSawtooth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarDivideMini {
            get {
                object obj = ResourceManager.GetObject("imgScalarDivideMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarMultiply {
            get {
                object obj = ResourceManager.GetObject("imgScalarMultiply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarMultiplyMini {
            get {
                object obj = ResourceManager.GetObject("imgScalarMultiplyMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarOperationBlock {
            get {
                object obj = ResourceManager.GetObject("imgScalarOperationBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarOperationBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgScalarOperationBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarSubtractMini {
            get {
                object obj = ResourceManager.GetObject("imgScalarSubtractMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScalarSumMini {
            get {
                object obj = ResourceManager.GetObject("imgScalarSumMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScaleBlock {
            get {
                object obj = ResourceManager.GetObject("imgScaleBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgScaleBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgScaleBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgShiftBlock {
            get {
                object obj = ResourceManager.GetObject("imgShiftBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgShiftBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgShiftBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSignalExtensionBlock {
            get {
                object obj = ResourceManager.GetObject("imgSignalExtensionBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSignalExtensionBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgSignalExtensionBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSine {
            get {
                object obj = ResourceManager.GetObject("imgSine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSplash {
            get {
                object obj = ResourceManager.GetObject("imgSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSquare {
            get {
                object obj = ResourceManager.GetObject("imgSquare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSubtractMini {
            get {
                object obj = ResourceManager.GetObject("imgSubtractMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSum {
            get {
                object obj = ResourceManager.GetObject("imgSum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSumMini {
            get {
                object obj = ResourceManager.GetObject("imgSumMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSwitchBlock {
            get {
                object obj = ResourceManager.GetObject("imgSwitchBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSwitchBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgSwitchBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTriangle {
            get {
                object obj = ResourceManager.GetObject("imgTriangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUniqueBlock {
            get {
                object obj = ResourceManager.GetObject("imgUniqueBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUniqueBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgUniqueBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpSampleBlock {
            get {
                object obj = ResourceManager.GetObject("imgUpSampleBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpSampleBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgUpSampleBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWavelet40x40 {
            get {
                object obj = ResourceManager.GetObject("imgWavelet40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWaveletBlock {
            get {
                object obj = ResourceManager.GetObject("imgWaveletBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWaveletBlockMini {
            get {
                object obj = ResourceManager.GetObject("imgWaveletBlockMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgXorMini {
            get {
                object obj = ResourceManager.GetObject("imgXorMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model threw a stack overflow exception.
        /// </summary>
        internal static string ModelThrewStackOverflow {
            get {
                return ResourceManager.GetString("ModelThrewStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document.
        /// </summary>
        internal static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string NewDocumentChar {
            get {
                return ResourceManager.GetString("NewDocumentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Size.
        /// </summary>
        internal static string PreviousSize {
            get {
                return ResourceManager.GetString("PreviousSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Finish.
        /// </summary>
        internal static string rampfinish {
            get {
                return ResourceManager.GetString("rampfinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Start.
        /// </summary>
        internal static string rampstart {
            get {
                return ResourceManager.GetString("rampstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program needs to be restarted in order to apply new settings..
        /// </summary>
        internal static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return only valid samples.
        /// </summary>
        internal static string returnonlyvalid {
            get {
                return ResourceManager.GetString("returnonlyvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value to zero in the end.
        /// </summary>
        internal static string returntozero {
            get {
                return ResourceManager.GetString("returntozero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample time interval.
        /// </summary>
        internal static string samplinginterval {
            get {
                return ResourceManager.GetString("samplinginterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rate (Hz).
        /// </summary>
        internal static string samplingrate {
            get {
                return ResourceManager.GetString("samplingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes before closing?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        internal static string scalaroperation_text {
            get {
                return ResourceManager.GetString("scalaroperation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        internal static string Signal {
            get {
                return ResourceManager.GetString("Signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First column contains signal name.
        /// </summary>
        internal static string signalnameinfirstcolumn {
            get {
                return ResourceManager.GetString("signalnameinfirstcolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal start time.
        /// </summary>
        internal static string signalstart {
            get {
                return ResourceManager.GetString("signalstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Templates.
        /// </summary>
        internal static string signaltemplates {
            get {
                return ResourceManager.GetString("signaltemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.waveletstudio.net.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Samples.
        /// </summary>
        internal static string sortsamples {
            get {
                return ResourceManager.GetString("sortsamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string templatename {
            get {
                return ResourceManager.GetString("templatename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use trigonometric table (faster).
        /// </summary>
        internal static string uselookuptable {
            get {
                return ResourceManager.GetString("uselookuptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet Studio.
        /// </summary>
        internal static string WaveletStudio {
            get {
                return ResourceManager.GetString("WaveletStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelet Studio Document.
        /// </summary>
        internal static string WaveletStudioDocument {
            get {
                return ResourceManager.GetString("WaveletStudioDocument", resourceCulture);
            }
        }
    }
}
