//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveletStudio.MainApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaveletStudio.MainApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column separator.
        /// </summary>
        internal static string columnseparator {
            get {
                return ResourceManager.GetString("columnseparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution Mode.
        /// </summary>
        internal static string convolutionmode {
            get {
                return ResourceManager.GetString("convolutionmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic (slower, uses less memory).
        /// </summary>
        internal static string dynamictrigonometricvalues {
            get {
                return ResourceManager.GetString("dynamictrigonometricvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before performing any operation is necessary to select a source. 
        ///Click in the Signal tab and select a signal source..
        /// </summary>
        internal static string errorinvalidoriginalsignal {
            get {
                return ResourceManager.GetString("errorinvalidoriginalsignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension size (0 to use next power of 2).
        /// </summary>
        internal static string extensionsize {
            get {
                return ResourceManager.GetString("extensionsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        internal static string fft {
            get {
                return ResourceManager.GetString("fft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string filepath {
            get {
                return ResourceManager.GetString("filepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Time.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency (Hz).
        /// </summary>
        internal static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon icoColor {
            get {
                object obj = ResourceManager.GetObject("icoColor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icoCopy {
            get {
                object obj = ResourceManager.GetObject("icoCopy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icoPaste {
            get {
                object obj = ResourceManager.GetObject("icoPaste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore first row.
        /// </summary>
        internal static string ignorefirstrow {
            get {
                return ResourceManager.GetString("ignorefirstrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the last sample.
        /// </summary>
        internal static string ignorelastsample {
            get {
                return ResourceManager.GetString("ignorelastsample", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap imgconvolution {
            get {
                object obj = ResourceManager.GetObject("imgconvolution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgconvolutionmini {
            get {
                object obj = ResourceManager.GetObject("imgconvolutionmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgcosine {
            get {
                object obj = ResourceManager.GetObject("imgcosine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgcsvfile {
            get {
                object obj = ResourceManager.GetObject("imgcsvfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgdividemini {
            get {
                object obj = ResourceManager.GetObject("imgdividemini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgdownsample {
            get {
                object obj = ResourceManager.GetObject("imgdownsample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgdownsamplemini {
            get {
                object obj = ResourceManager.GetObject("imgdownsamplemini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgexportcsv {
            get {
                object obj = ResourceManager.GetObject("imgexportcsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgfft {
            get {
                object obj = ResourceManager.GetObject("imgfft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgfftmini {
            get {
                object obj = ResourceManager.GetObject("imgfftmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgifft {
            get {
                object obj = ResourceManager.GetObject("imgifft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgifftmini {
            get {
                object obj = ResourceManager.GetObject("imgifftmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgmultiplymini {
            get {
                object obj = ResourceManager.GetObject("imgmultiplymini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgoperation {
            get {
                object obj = ResourceManager.GetObject("imgoperation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgoperationmini {
            get {
                object obj = ResourceManager.GetObject("imgoperationmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgramp {
            get {
                object obj = ResourceManager.GetObject("imgramp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgsawtooth {
            get {
                object obj = ResourceManager.GetObject("imgsawtooth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgscalar {
            get {
                object obj = ResourceManager.GetObject("imgscalar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgscalardividemini {
            get {
                object obj = ResourceManager.GetObject("imgscalardividemini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgscalarmini {
            get {
                object obj = ResourceManager.GetObject("imgscalarmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgscalarmultiplymini {
            get {
                object obj = ResourceManager.GetObject("imgscalarmultiplymini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgscalarsubtractmini {
            get {
                object obj = ResourceManager.GetObject("imgscalarsubtractmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgscalarsummini {
            get {
                object obj = ResourceManager.GetObject("imgscalarsummini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgsine {
            get {
                object obj = ResourceManager.GetObject("imgsine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgsplash {
            get {
                object obj = ResourceManager.GetObject("imgsplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgsquare {
            get {
                object obj = ResourceManager.GetObject("imgsquare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgsubtractmini {
            get {
                object obj = ResourceManager.GetObject("imgsubtractmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgsummini {
            get {
                object obj = ResourceManager.GetObject("imgsummini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgtriangle {
            get {
                object obj = ResourceManager.GetObject("imgtriangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgwavelet {
            get {
                object obj = ResourceManager.GetObject("imgwavelet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgwavelet40x40 {
            get {
                object obj = ResourceManager.GetObject("imgwavelet40x40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgwaveletmini {
            get {
                object obj = ResourceManager.GetObject("imgwaveletmini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Finish.
        /// </summary>
        internal static string rampfinish {
            get {
                return ResourceManager.GetString("rampfinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp Start.
        /// </summary>
        internal static string rampstart {
            get {
                return ResourceManager.GetString("rampstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return only valid samples.
        /// </summary>
        internal static string returnonlyvalid {
            get {
                return ResourceManager.GetString("returnonlyvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return value to zero in the end.
        /// </summary>
        internal static string returntozero {
            get {
                return ResourceManager.GetString("returntozero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample time interval.
        /// </summary>
        internal static string samplinginterval {
            get {
                return ResourceManager.GetString("samplinginterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Rate (Hz).
        /// </summary>
        internal static string samplingrate {
            get {
                return ResourceManager.GetString("samplingrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        internal static string scalaroperation_text {
            get {
                return ResourceManager.GetString("scalaroperation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First column contains signal name.
        /// </summary>
        internal static string signalnameinfirstcolumn {
            get {
                return ResourceManager.GetString("signalnameinfirstcolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal start time.
        /// </summary>
        internal static string signalstart {
            get {
                return ResourceManager.GetString("signalstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Templates.
        /// </summary>
        internal static string signaltemplates {
            get {
                return ResourceManager.GetString("signaltemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string templatename {
            get {
                return ResourceManager.GetString("templatename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use trigonometric table (faster).
        /// </summary>
        internal static string uselookuptable {
            get {
                return ResourceManager.GetString("uselookuptable", resourceCulture);
            }
        }
    }
}
